version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"      # Nginx
      - "3000:3000"  # Backend API
      - "8000:8000"  # DynamoDB Local
    environment:
      - NODE_ENV=development
      - AWS_REGION=local
    volumes:
      - dynamodb-data:/inkpandas/data

volumes:
  dynamodb-data: